### ISSUE TITLE
Incompatible filename can crash the server

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#184]
We want the uploaded files to have the name format of `store_name-supplier_name-etc.csv` but this shouldn't crash our system. Non `fail-fast` checks should detect & alert users of an issue with the filename format ... on either client or server side without bringing the site down.

### Problem # 1

Use of filename `test.csv`, server crashes as shown while testing:
```
web-1 | 2016-07-15T18:52:27.810914744Z Fri, 15 Jul 2016 18:52:27 GMT server:middleware:accessLogger DEBUG 10.7.0.8-X-X req POST /api/containers/5788954fe37be3010024d7f1/upload
web-1 | 2016-07-15T18:52:27.826652929Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container TRACE 10.7.0.8-X-X Container > beforeRemote > upload
web-1 | 2016-07-15T18:52:27.826886157Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X Container > beforeRemote > upload > userId 5788954fe37be3010024d7f1
web-1 | 2016-07-15T18:52:27.827447391Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X Container > beforeRemote > upload > Container does not exist > let us create a new one
web-1 | 2016-07-15T18:52:27.829384566Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X Container > beforeRemote > upload > Created a new container 5788954fe37be3010024d7f1
web-1 | 2016-07-15T18:52:27.835744156Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X Container > afterRemote > upload
web-1 | 2016-07-15T18:52:27.836181634Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X Container > afterRemote > upload  > FILE(S) UPLOADED: %j [ { container: '5788954fe37be3010024d7f1',
web-1 | 2016-07-15T18:52:27.836241736Z     name: 'test.csv',
web-1 | 2016-07-15T18:52:27.836248796Z     type: 'text/csv',
web-1 | 2016-07-15T18:52:27.836252645Z     size: 59 } ]
web-1 | 2016-07-15T18:52:27.866666598Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X parsed csv rows: 3
web-1 | 2016-07-15T18:52:27.866915888Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X #1 create a new Reportmodel
web-1 | 2016-07-15T18:52:27.867401198Z Fri, 15 Jul 2016 18:52:27 GMT common:models:container DEBUG 10.7.0.8-X-X regex with storeName test.csv
web-1 | 2016-07-15T18:52:27.867965796Z 
web-1 | 2016-07-15T18:52:27.870321996Z TypeError: Cannot call method 'replace' of undefined
web-1 | 2016-07-15T18:52:27.870339098Z     at createReportModel (/apps/warehouse/common/models/container.js:159:33)
web-1 | 2016-07-15T18:52:27.870344356Z     at Converter.<anonymous> (/apps/warehouse/common/models/container.js:74:7)
web-1 | 2016-07-15T18:52:27.870348944Z     at Converter.emit (events.js:95:17)
web-1 | 2016-07-15T18:52:27.870353032Z     at Converter.<anonymous> (/apps/warehouse/node_modules/csvtojson/libs/core/Converter.js:51:10)
web-1 | 2016-07-15T18:52:27.870357060Z     at Converter.emit (events.js:117:20)
web-1 | 2016-07-15T18:52:27.870360690Z     at _stream_readable.js:944:16
web-1 | 2016-07-15T18:52:27.870365043Z     at /apps/warehouse/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
web-1 | 2016-07-15T18:52:27.870368872Z     at /apps/warehouse/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
web-1 | 2016-07-15T18:52:27.870372786Z     at process._tickDomainCallback (node.js:502:13)
web-1 | 2016-07-15T18:52:27.870376892Z     at process.fallback (/apps/warehouse/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:450:15)
```

### Problem # 2

Use of filename `Lavish_Apparel-CSC.csv`, server crashes as shown while testing:
```
web-1 | 2016-07-15T19:04:50.582430655Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X Container > afterRemote > upload  > FILE(S) UPLOADED: %j [ { container: '5788954fe37be3010024d7f1',
web-1 | 2016-07-15T19:04:50.582459945Z     name: 'Lavish_Apparel-CSC.csv',
web-1 | 2016-07-15T19:04:50.582471001Z     type: 'text/csv',
web-1 | 2016-07-15T19:04:50.582482467Z     size: 59 } ]
web-1 | 2016-07-15T19:04:50.605696311Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X parsed csv rows: 3
web-1 | 2016-07-15T19:04:50.605920680Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X #1 create a new Reportmodel
web-1 | 2016-07-15T19:04:50.606209748Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X regex with storeName Lavish.Apparel
web-1 | 2016-07-15T19:04:50.606822821Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X regex with supplierName CSC.csv
web-1 | 2016-07-15T19:04:50.607041511Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container DEBUG 10.7.0.8-X-X modified regex with supplierName ^CSC.csv$
web-1 | 2016-07-15T19:04:50.622352404Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container TRACE 10.7.0.8-X-X storeModelInstance { name: 'Lavish Apparel',
web-1 | 2016-07-15T19:04:50.622397168Z   country: 'US',
web-1 | 2016-07-15T19:04:50.622780882Z   api_id: '8d430d3e-4df1-11e2-b1f5-4040782fde00',
web-1 | 2016-07-15T19:04:50.622804586Z   userModelToStoreModelId: 5788954fe37be3010024d7f4,
web-1 | 2016-07-15T19:04:50.622814039Z   storeConfigModelToStoreModelId: 57889550e37be3010024d7f9,
web-1 | 2016-07-15T19:04:50.622820046Z   objectId: 57889550e37be3010024d7fb }
web-1 | 2016-07-15T19:04:50.637909863Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container TRACE 10.7.0.8-X-X supplierModelInstance null
web-1 | 2016-07-15T19:04:50.644661069Z Fri, 15 Jul 2016 19:04:50 GMT common:models:container ERROR 10.7.0.8-X-X Container > afterRemote > upload > end_parsed 
web-1 | 2016-07-15T19:04:50.644703192Z  Could not find a matching supplier for: Lavish_Apparel-CSC.csv
```

### Problem # 3
File naming conventions that currently work:
- `store_name-supplier_name-etc.csv`

Other formats which should *also* work:
- `store_name-supplier_name.csv`
- `store_name-supplier_name.CSV`
- `store_name-supplier_name-.CSV`

**Comment by pulkitsinghal** [comment]
In short:
1. server should not crash - add try/catch where ever needed and safely report the problem back to the browser/client
2. show the meaningful part of the error in the default error display area

**Comment by pulkitsinghal** [comment]
Thanks @ysg410 - I tweaked and merged it. Next time lets plan on adding unit, or functional or e2e tests for stuff like this.
