### ISSUE TITLE
provide better error capture and identification

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#63]
... provide better error capture and identification for failures to read from seed.json in boot scripts

@Chhaya-rai was **blocked** because an error which originated in a boot script, provided no stack trace and made it look like the grunt plugins were failing ... we only identified the culprit through sheer luck ... the code needs to be better than that otherwise fellow developers or devops will suffer from regular heart attacks.

**Comment by pulkitsinghal** [comment]
```
Running "localtunnel:development" (localtunnel) task
Fatal error: Cannot read property '0' of undefined
```
See how misleading that is?

**Comment by pulkitsinghal** [comment]
Now you should see something more informative like:

```
Running "localtunnel:development" (localtunnel) task
Trace: TypeError: Cannot read property '0' of undefined
  at /Users/pulkitsinghal/dev/w2/server/boot/create-model-instances-01.js:159:51
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:622:18
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:1342:5
  at allCb (/Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:1281:7)
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:371:7
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at process._tickDomainCallback (node.js:492:13)
  at process.<anonymous> (/Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)

  at /Users/pulkitsinghal/dev/w2/server/boot/create-model-instances-01.js:420:19
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:622:18
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:1342:5
  at allCb (/Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/dao.js:1281:7)
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:371:7
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at /Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at process._tickDomainCallback (node.js:492:13)
  at process.<anonymous> (/Users/pulkitsinghal/dev/w2/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)

Fatal error: Cannot read property '0' of undefined
```
